[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "cd server && npm install --only=production",
  "cd ../client && npm install --legacy-peer-deps && npm run build"
]

[start]
cmd = "cd server && node index.js"

