[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[phases.install]
cmds = [
  "sh -c 'cd server && npm install --only=production'",
  "sh -c 'cd client && npm install --legacy-peer-deps && npm run build'"
]

[start]
cmd = "sh -c 'cd server && node index.js'"

